export const background = "rgb(0, 0, 0)";
export const currentLine = "#44475a";
export const Foreground = "#f8f8f2";
export const Comment = "#6272a4";
export const Cyan = "#8be9fd"; //
export const Green = "#50fa7b";
export const Orange = "#ffb86c";
export const Pink = "#ff79c6";
export const purple = "#bd93f9";
export const Red = "#ff5555";
export const Yellow = "#fadf00";
export const myGray = "#646060";
